### ISSUE TITLE
test database script is not present

### ISSUE THREAD

**Issue by peschkaj** [steffengy/tiberius#1]
Integration tests are present that rely on a `test` database. Unfortunately, there's no script present to create the database.

Is this something you could script with SSMS and re-create?

If not, would you be open to tests being re-written to run against system databases?

**Comment by steffengy** [comment]
@peschkaj 
That's definitely something on the todo list.
Originally I planned to add this with enabling appveyor support at 
a later more stable state, but I guess it makes sense to add the current state of
sql files.

**Comment by peschkaj** [comment]
Thanks for that!

Having test schema that moves isn't a huge deal as long as we can re-create
schema for testing.

I have some tests to write around using parameterized SQL, which should be
more agreeable to most folks that `sp_prepare` and `sp_execute`. Hopefully
I can get that working now that there's schema!

On Sat, Jun 11, 2016 at 12:47 AM Steffen Butzer <notifications@github.com>
wrote:

> @peschkaj <https://github.com/peschkaj>
> That's definitely something on the todo list.
> Originally I planned to add this with enabling appveyor support at
> a later more stable state, but I guess it makes sense to add the current
> state of
> sql files.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/steffengy/tiberius/issues/1#issuecomment-225342873>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEXkoq0oP5Izhjf1_pHGSn53ZkHeyHlks5qKmgNgaJpZM4IzbU5>
> .
>
-- 

Jeremiah Peschka
