### ISSUE TITLE
Database choice

### ISSUE THREAD

**Issue by ms705** [steffengy/tiberius#10]
The current master branch no longer supports DB selection via the connection string (as `old` did), but when I try to choose a DB via SQL (`use db;`), I hit the following error:
```
thread 'main' panicked at 'resultset: unexpected token: Info(TokenInfo { number: 5701, state: 1, class: 0, message: "Changed database context to \'test\'.", server: "tbilisi", procedure: "", line: 1 })', src/query.rs:85
```
This is fixed easily enough by covering the `TokenInfo` case in the match, but even if I do so (returning 'false`), subsequent `SELECT` queries fail to return any results. The same queries work when not choosing a custom database context.

Minimal example:
```rust
extern crate futures;
extern crate futures_state_stream;
extern crate tokio_core;
extern crate tiberius;

use futures_state_stream::StateStream;
use tokio_core::reactor::Core;
use tiberius::SqlConnection;
use tiberius::stmt::ResultStreamExt;

fn main() {
    let dbn = "server=tcp:127.0.0.1,1433;username=test;password=T3stT3st;";

    let mut core = Core::new().unwrap();
    let cf = SqlConnection::connect(core.handle(), dbn);
    let c = core.run(cf).unwrap();

    // let f = c.simple_exec("use test;").and_then(|r| r).collect();
    // let (_, c) = core.run(f).unwrap();

    let f2 = c.simple_query("SELECT 1+2").for_each_row(|r| {
        println!("{:?}", r);
        Ok(())
    });
    core.run(f2).unwrap();
}
```
If I uncomment the two commented lines (and add `TokenInfo` at line 84 of `src/query.rs`), the program runs but prints no result rows; with these lines commented out, it works fine.

For reference, my addition to `src/query.rs` is this:
```diff
--- a/src/query.rs
+++ b/src/query.rs
@@ -81,6 +81,7 @@ impl<I: BoxableIo, R: StmtResult<I>> StateStream for ResultSetStream<I, R> {
                                     false
                                 }
                             },
+                            TdsResponseToken::Info(_) => false,
                             tok => panic!("resultset: unexpected token: {:?}", tok)
                         }
                     }
```

**Comment by steffengy** [comment]
should be "fixed" in: https://github.com/steffengy/tiberius/commit/f118076a583b1161c559d41e152c55e0d14e2ce8

**Comment by ms705** [comment]
Thanks, that does indeed work around the problem.

**Comment by steffengy** [comment]
@ms705 
should be implemented now, let me know if there are any issues!
