### ISSUE TITLE
Saving chrono::NaiveDateTime panics with TokenDone cur_cmd: 224

### ISSUE THREAD

**Issue by nevi-me** [steffengy/tiberius#100]
I'm inserting a record into my database, and one of the columns in the insert is a `DATETIME2` type. I'm using `0.3.{1 || 2}`, and I've noticed the below:

* The insert saves correctly, as I can see the datetime2 being populated
* The insert throws an error though, with the below error
* Removing the datetime2 parameter, and not saving any value there, results in the save not panicing.

```rust
thread '<unnamed>' panicked at 'query: unexpected token: DoneProc(TokenDone { status: (empty), cur_cmd: 224, done_rows: 0 })', C:\Users\nedipale\.cargo\registry\src\github.com-1ecc6299db9ec823\tiberius-0.3.2\src\query.rs:158:22
n
```

For reference, my query looks like:

```rust
let timestamp = chrono::NaiveDateTime::from_timestamp(three, 0);
conn.query("
    INSERT INTO my_table (
        one, two, three, the_datetime2_col, five, six
    ) values (@P1, @P2, @P3, @P4, @P5, @P6)",
    &[
        &one.as_str(),
        &two.as_str(),
        &three.as_str(),
        &timestamp,
        &five.as_str(),
        &true
    ]
)

```

Do you know what could be causing this?

**Comment by steffengy** [comment]
Well, does using `exec` insteadof `query` work ?

**Comment by nevi-me** [comment]
It returns `ExecResult` which from the docs is `A single resultset yielding the status of query execution (currently the amount of affected rows)`.
I wanted to execute an insert, and get the ID of the inserted record back. Using `exec` still returns a result count of 0 even though I can see that the record is inserted in the database.

Using exec no longer blocks my work though, but do you mind if I leave this issue open, so that I can come back to it later when I make more time; to properly reproduce it? Thanks!

**Comment by steffengy** [comment]
AFAIK the proper way to do this would be to add an OUTPUT clause to the INSERT and 
use query.

Something like:
```sql
INSERT INTO my_table(one, two)
OUTPUT INSERTED.ID
VALUES (@P1, @P2)
```
