### ISSUE TITLE
Do you know of this effort to kickstart a database-wg for Rust?

### ISSUE THREAD

**Issue by brokenthorn** [steffengy/tiberius#101]
Hello,

I couldn't find another way to contact you, but I thought you should know about a new effort that is being kickstarted by [@spacecookie](https://github.com/spacekookie) announced at [Rust Internals](https://internals.rust-lang.org/t/kickstarting-a-database-wg/9696) to build a database working group for Rust.

**Comment by steffengy** [comment]
Yeah, I'm aware of it. We'll see where it goes.
