### ISSUE TITLE
SSRP/SQL Browser Service

### ISSUE THREAD

**Issue by wokket** [steffengy/tiberius#110]
Hi,

I started playing with Tiberius, but ran into issues connecting to a named instance.  This was caused by a (previously unknown to me) behaviour where SQL named instances run on a random high port by default, and require a query to the SQL Server Browser Service (using [SSRP](https://docs.microsoft.com/en-us/openspecs/windows_protocols/mc-sqlr/f9e7c304-ef7e-4d5b-9104-a3807c93436f) over UDP) to get the actual connection information for a named instance.

I started looking into building a SSRP library, but was interested to know whether you saw this as:
- something tiberius should handle (as a SQL client), or
- something to be kept external to tiberius (as it's a TDS library).

Cheers,

**Comment by steffengy** [comment]
That's already implemented?
https://github.com/steffengy/tiberius/blob/77042cc2ed2770f2b8dc0f85faafb6184ce7e5e3/tiberius/src/lib.rs#L610

**Comment by steffengy** [comment]
If you use a connection string, you need to use `server=yourserver\\instancename`, as with the .NET implementation.

**Comment by wokket** [comment]
Hmmm, right you are!

I'm not sure how I both missed that code when I searched for it, or why I'm still having troubles but I'll keep digging as it's obviously my issue!

A side note: Is that instance name correctly NUL terminated in the SSRP message? 

Thanks for getting back to me :+1:

**Comment by steffengy** [comment]
Whats the behavior you're observing? Is the SQL Browser service running?

**Comment by wokket** [comment]
I only have a SQL Express named instance running on this machine.  I was totally unable to get the `connect_to_named_instance` test to pass, error was 'connection string pointing into the void.'.  I've reverted to the github codebase (having stepped all over the in-code conn strings/env vars) and it is now connecting fine.... typical.

I have a suspicion that something in the recent Insider/WSL2 builds is playing havoc with my local TCP connectivity, but it's just as likely a total SNAFU from me.
