### ISSUE TITLE
Use of both an instance name and port results in `host not found`

### ISSUE THREAD

**Issue by yatesco** [steffengy/tiberius#113]
Hi,

Using either an instance or a port works, but using both fails.

Works:
 - `Server=tcp:my-host\\my-instance;integratedSecurity=false;encrypt=false;trustservercertificate=true;user=my-user;password=my-password;database=my-database;` 
 - `Server=tcp:my-host,1433;integratedSecurity=false;encrypt=false;trustservercertificate=true;user=my-user;password=my-password;database=my-database;`

Doesn't work:
- `Server=tcp:my-host\\my-instance,1433;integratedSecurity=false;encrypt=false;trustservercertificate=true;user=my-user;password=my-password;database=my-database;`

**Comment by steffengy** [comment]
While the error message is suboptimal, an error is expected.
You either specify a TCP port or an instance name, which is used to determine the TCP port by asking the SQL Server Browser service via UDP.

**Comment by yatesco** [comment]
Ah OK, thanks, I’ll close
