### ISSUE TITLE
Which version or branch to use?

### ISSUE THREAD

**Issue by svanharmelen** [steffengy/tiberius#114]
I've just started a project that needs a connection to an MSSQL server and found this nice package providing the needed building blocks.

The question I have is about what version or branch to use? I noticed that you mentioned that `v0.3` will not be updated anymore, so I was wondering if the `async_await` branch is already stable enough for us to use (or course understanding that the API can still change, but that's fine)?

Thanks!

**Comment by steffengy** [comment]
No it is not, it's a first sketch. 
I wouldn't recommend 0.3 or any version for anything production related at this time.

**Comment by svanharmelen** [comment]
So would an older v0.2 be OK to use? Or do you have any other (versions or packages) suggestions?

The use of MSSQL is limited to running 1 (identical) query every 5 minutes. So our usecase is reasonably straight forward.

Thanks!

**Comment by steffengy** [comment]
Generally 0.3 should be the most stable version, but is a bit outdated in terms of futures version...

I'am not aware of any other library besides ODBC and there are also there are afaik no FreeTDS bindings for rust.

**Comment by svanharmelen** [comment]
I was just looking at ODBC as well, but think I’ll first take v0.3 for a spin. Thanks again for the feedback!
