### ISSUE TITLE
Migrate NTLM to winauth

### ISSUE THREAD

**Issue by steffengy** [steffengy/tiberius#12]
https://github.com/steffengy/winauth-rs

(first we need to flesh out winauth APIs, implement NTLMv2 server, etc.)

**Comment by ctaggart** [comment]
I see that commits made it to master for this. 👍 
https://github.com/steffengy/tiberius/commit/f463bff45209fa8e37e53d51d2e99cb6e23b7c9f

**Comment by steffengy** [comment]
Yeah nothing exciting.

Simple summary of the changes:
The SSO portion was extracted into a new crate,
which also supports NTLMv2 in a platform-independent way.

So Windows Authentication with credentials is now possible using NTLMv2.

Kerberos and NTLMv2 server implementations will eventually follow in the winauth crate.
