### ISSUE TITLE
`'invalid token received 0xa9'` when using `ORDER BY`

### ISSUE THREAD

**Issue by gugi9000** [steffengy/tiberius#13]
When I make a query that sorts a table:

```SELECT [Name] ,[Email] FROM [RIS].[dbo].[Employee] ORDER BY NAME```

I get a panic: `thread 'main' panicked at 'invalid token received 0xa9', C:\Users\bs\.cargo\git\checkouts\tiberius-efcdb30e5dbea5fc\28d2aa5\src\transport.rs:347`

If I remove the ORDER BY it runs just fine.

The token 0xA9 is in fact the [ORDER BY token](http://www.freetds.org/tds.html#t169) :-)

**Comment by steffengy** [comment]
yep I'll look into that soon.

**Comment by steffengy** [comment]
@gugi9000 
Should be fixed in the latest master

**Comment by gugi9000** [comment]
Now I get `invalid token received 0x0` or `invalid token received 0x1`

0x0 can be triggered with:
```
SELECT [Name]
  FROM [Employee]
  ORDER BY Name```

**Comment by steffengy** [comment]
@gugi9000 
yep small logic flaw, should be fixed now.

**Comment by gugi9000** [comment]
confirmed :-)
