### ISSUE TITLE
support SSL to be able to connect to Azure SQL

### ISSUE THREAD

**Issue by davidpodhola** [steffengy/tiberius#15]
This is a great library I am now using in [Example Rust codebase containing real world examples (CRUD, auth, advanced patterns, etc) that adheres to the RealWorld API spec.](https://github.com/hsharpsoftware/rust-realworld-example-app).

However we would need to add SSL to be able to connect to Azure SQL. Could you please indicate where to start? Thanks!

**Comment by steffengy** [comment]
I started working on that but hit a roadblock (and didn't need it myself).

I'll look into it for you and will hopefully get it to land.

**Comment by davidpodhola** [comment]
Thanks, I would be happy to help if there is something at my very beginner level :-)

**Comment by steffengy** [comment]
@davidpodhola 
It might work using the latest master now.

If you don't explicitly disable the TLS feature in your `cargo.toml`, 
it should be able to use encryption, if the server requests that.

**Comment by davidpodhola** [comment]
@steffengy great, thanks, it works against Azure SQL Database now! Very impressed and happy.

However is there a possibility to support connection string like `"server=tcp:127.0.0.1,1433;integratedSecurity=true;"` again?

If I add `encrypt=true;` I get `A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.` back. I assume using a guide like [Using a self-signed SSL certificate with SQL Server](https://thedataspecialist.wordpress.com/2013/03/12/using-a-self-signed-ssl-certificate-with-sql-server/) would fix this, but is not there a quick fix to enable this back please? Thanks!

**Comment by steffengy** [comment]
> However is there a possibility to support connection string like "server=tcp:127.0.0.1,1433;integratedSecurity=true;" again?

What issue do you have using this connection string?
This should still be supported.

> If I add encrypt=true; I get A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.

The issue there is that the self-signed certificate is not trusted on your computer.
`trustservercertificate` cannot be implemented as of now, since `tokio-nativetls`
doesn't support that.

The only ways around it currently are:
a) Disable encryption (which is safe since it's a connection to localhost anyways)
b) Use a valid certificate

**Comment by davidpodhola** [comment]
Sorry for the confusion. 

The connection string **is supported**, but if I run a query with connection string like `"server=tcp:127.0.0.1,1433;integratedSecurity=true;"`, I get

`thread '<unnamed>' panicked at 'not yet implemented', C:\Users\david.podhola\.cargo\git\checkouts\tiberius-efcdb30e5dbea5fc\ffbb388\src\[lib.rs:314](https://github.com/steffengy/tiberius/blob/master/src/lib.rs#L314)`

I tried to simply return `SqlConnectionNewState::LoginSend` there, but it did not help.

**Comment by steffengy** [comment]
Ah right, the problem is that the server and your client negotiate to handle only the login encrypted (since both support encryption, this is not yet implemented and would fail with the same certificate error in your case).

The only possibility to entirely disable encryption at the moment is using something like:
```
tiberius = { git = 'https://github.com/steffengy/tiberius', default-features = false, features = ["chrono"] }
```
in your Cargo.toml.

This will compile without TLS support and will not work on Azure without
changing it back.
Is that an issue for you?

**Comment by davidpodhola** [comment]
Thanks, that would work for me very well, but unfortunately it does not build for me now :-(
I tries to move `TransportStream` to allow building without `#[cfg(feature = "tls")]`, but looks like it is more complicated.

![capture](https://cloud.githubusercontent.com/assets/436605/26282663/fb760b64-3e15-11e7-9f95-f99fd837e8a7.PNG)

```
   Compiling tiberius v0.2.0 (file:///C:/Users/david.podhola/Documents/S/tiberius)
error[E0432]: unresolved import `transport::TransportStream`
   --> C:\Users\david.podhola\Documents\S\tiberius\src\lib.rs:110:35
    |
110 | use transport::{Io, TdsTransport, TransportStream};
    |                                   ^^^^^^^^^^^^^^^ no `TransportStream` in `transport`

error[E0433]: failed to resolve. Could not find `tls` in `transport`
   --> C:\Users\david.podhola\Documents\S\tiberius\src\lib.rs:301:58
    |
301 |                                     let wrapped_stream = transport::tls::TlsTdsWrapper::new(stream, self.transport.inner.next_packet_id);
    |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `tls` in `transport`

error[E0433]: failed to resolve. Could not find `tls` in `transport`
   --> C:\Users\david.podhola\Documents\S\tiberius\src\lib.rs:307:54
    |
307 |                                     let tls_stream = transport::tls::connect_async(wrapped_stream, host);
    |                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `tls` in `transport`

warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> C:\Users\david.podhola\Documents\S\tiberius\src\transport.rs:205:1
    |
205 | pub type TlsStream<S: Io> = S;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0392]: parameter `I` is never used
   --> C:\Users\david.podhola\Documents\S\tiberius\src\lib.rs:176:28
    |
176 | enum SqlConnectionNewState<I: Io> {
    |                            ^ unused type parameter
    |
    = help: consider removing `I` or using a marker such as `std::marker::PhantomData`

error[E0392]: parameter `I` is never used
   --> C:\Users\david.podhola\Documents\S\tiberius\src\lib.rs:252:32
    |
252 | pub struct SqlConnectionFuture<I: BoxableIo> {
    |                                ^ unused type parameter
    |
    = help: consider removing `I` or using a marker such as `std::marker::PhantomData`

error[E0392]: parameter `I` is never used
   --> C:\Users\david.podhola\Documents\S\tiberius\src\lib.rs:411:31
    |
411 | pub struct InnerSqlConnection<I: BoxableIo> {
    |                               ^ unused type parameter
    |
    = help: consider removing `I` or using a marker such as `std::marker::PhantomData`

error: aborting due to 3 previous errors

error: Could not compile `tiberius`.
```

**Comment by steffengy** [comment]
Sorry, oversight on my part, should work now.

**Comment by davidpodhola** [comment]
Terrific, so both

- `connection_string = "server=tcp:hsharpXXX.database.windows.net,1433;uid=YYY@hsharpXXX.database.windows.net;password=ZZZ;encrypt=true;"`
- `connection_string = "server=tcp:127.0.0.1,1433;integratedSecurity=true;"`

with [corresponding Cargo.toml changes](https://github.com/steffengy/tiberius/issues/15#issuecomment-302923733) works now.

Thanks a lot!
