### ISSUE TITLE
how to represent NULLable nvarchar

### ISSUE THREAD

**Issue by davidpodhola** [steffengy/tiberius#17]
Thanks for fixing #16. 

Also please forgive my "iterative" way of work and not using the best approaches sometimes.

I now try to understand how to handle NULL. If I have a piece of code like here

                    let getUser = SqlConnection::connect(sql.handle(), connection_string.as_str() )
                        .and_then(|conn| conn.simple_query(                            
                            format!("SELECT [Email],[Token],[UserName],[Bio],[Image] FROM [dbo].[Users]
                                WHERE [Email] = '{1}' --{0}", &**databaseName, 
                                str::replace( &logged_in_user, "'", "''" )
                            )
                        ).for_each_row(|row| {
                            let email : &str = row.get(0);
                            let token : &str = row.get(1);
                            let user_name : &str = row.get(2);
                            let bio : &str = row.get(3);
                            let image : &str = row.get(4);
                            result = Some(User{ 
                                email:email.to_string(), token:token.to_string(), bio:bio.to_string(),
                                image:image.to_string(), username:user_name.to_string()
                            });
                            Ok(())
                        })
                    );

it fails with

`thread '<unnamed>' panicked at 'called "Result::unwrap()" on an "Err" value: Conversion("cannot interpret the given column data as an &\'a strvalue")', src\libcore\result.rs:859`

Couldy you please suggest how should we work with `NULL` here? So far (after using e.g. [FSharp.Data.SqlClient](http://fsprojects.github.io/FSharp.Data.SqlClient/)) I have used different approaches incl. using "special invalid" int values (`-1`) instead of `NULL` etc.

**Comment by steffengy** [comment]
Using `Option<&str>` as variable type should work and do what you want, right?

**Comment by davidpodhola** [comment]
Yes, exactly and it is also the most intuitive way I think, thanks.

_I was trying with `Option<String>`, still a novice too much to rust..._

**Comment by steffengy** [comment]
Also I looked through your code and noticed you use very much manual escaping
(which won't prevent a sql injection)

Any reason you don't use prepared statements there?

**Comment by davidpodhola** [comment]
Yes, this is indeed very wrong. Oh, it seems I now understand 

> **Warning:** Do not use `simple_query` with user-specified data. Resort to prepared statements for that.

Thank you for pointing this out. I simply overlooked it, I was thinking maybe it is not supported yet.
