### ISSUE TITLE
Simple example needed

### ISSUE THREAD

**Issue by kingcocomango** [steffengy/tiberius#18]
I understand documentation is low on the list, but could you provide a minimal working example?
I cant figure out how to build a connection, or the typical workflow for using this library.

**Comment by steffengy** [comment]
Have you taken a look at the docs?
If not, was the docs.rs badge too subtile on the github/crates.io page?
If so, I'll add a more explicit link also

https://docs.rs/tiberius

Let me know if there's any aspect that should be documented more detailed.
(Any general feedback/usability issues are general appreciated!)

**Comment by kingcocomango** [comment]
Oh my, I did miss it.
That and checking the todo list had documentation unmarked, so I assume it didnt exist yet.
Thanks for the fast feedback!

**Comment by kingcocomango** [comment]
Running the simple example gets me 
`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 10057, message: "A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied." } })', src\libcore\result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
`

I'm using cygwin rustc & cargo

**Comment by steffengy** [comment]
That is really strange.
Can you run with `RUST_BACKTRACE=1`?

Also is there any reason you're using CYGWIN over MINGW/MSVC?
Even if so, could you try if this issue persists using either one of them,
to see if it's related to cygwin?

**Comment by kingcocomango** [comment]
with backtrace on this is what I get 
`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 10057, message: "A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied." } })', src\libcore\result.rs:859
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<collections::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:495
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:471
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:69
   8: core::result::unwrap_failed<tiberius::TdsError>
             at C:\projects\rust\src\libcore\macros.rs:29
   9: core::result::Result<tiberius::SqlConnection<alloc::boxed::Box<BoxableIo>>, tiberius::TdsError>::unwrap<tiberius::SqlConnection<alloc::boxed::Box<BoxableIo>>,tiberius::TdsError>
             at C:\projects\rust\src\libcore\result.rs:737
  10: lerngui::main
             at ./src\main.rs:84
  11: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  12: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  13: main
  14: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  15: BaseThreadInitThunk
`
I misspoke, while im using the cygwin shell I installed rustc & cargo through the installer on their website, which uses MSV AFAIK. I ran the build and execution in a command prompt, and it has the same issue

**Comment by steffengy** [comment]
Okay thanks for the clarification, I'll have to look into this.

My first suggestion would be that TCP isn't enabled for SQL server (which is the default).

https://technet.microsoft.com/en-us/library/hh231672(v=sql.110).aspx

**Comment by kingcocomango** [comment]
Well. That fixed that issue and now I have 
`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Protocol("Error { repr: Os { code: -2146762487, message: \"A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.\" } }")', src\libcore\result.rs:859
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<collections::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:495
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:471
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:69
   8: core::result::unwrap_failed<tiberius::TdsError>
             at C:\projects\rust\src\libcore\macros.rs:29
   9: core::result::Result<tiberius::SqlConnection<alloc::boxed::Box<BoxableIo>>, tiberius::TdsError>::unwrap<tiberius::SqlConnection<alloc::boxed::Box<BoxableIo>>,tiberius::TdsError>
             at C:\projects\rust\src\libcore\result.rs:737
  10: lerngui::main
             at ./src\main.rs:84
  11: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  12: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  13: main
  14: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  15: BaseThreadInitThunk
`

Is this an issue on my end, or a problem with 'Windows Authentication' or ?

**Comment by steffengy** [comment]
The issue is with the certificate.
Either use a proper certificate (trusted by your local system) or disable SSL (only recommended for localhost).

Since Encryption is only supported for a few days, this is still very rough:
And also something that should be documented, will take  look at that later:

# Creating a trusted self-signed certificate
The following powershell creates and trusts a self-signed SSL certificate
```powershell
$cert = New-SelfSignedCertificate -DnsName $serverName,localhost -CertStoreLocation cert:\LocalMachine\My
$rootStore = Get-Item cert:\LocalMachine\Root
$rootStore.Open("ReadWrite")
$rootStore.Add($cert)
$rootStore.Close();
```
This also has to be chosen as active certificate in the SQL Server Configuration.
https://support.microsoft.com/en-us/help/316898/how-to-enable-ssl-encryption-for-an-instance-of-sql-server-by-using-microsoft-management-console

# Disabling SSL/Encryption entirely (only recommended for localhost)
Currently this is only possible by doing something like:
```toml
tiberius = { version = "0.X", default-features=false,features=["chrono"] }
```
in your cargo.toml.

In the future `TrustServerCertificate` will eventually be supported in the query
string, that at the moment unfortunately isn't trivially implementable,
without support for that landing in underlying libraries.

**Comment by kingcocomango** [comment]
I disabled SSL as I am using localhost, and now it runs without panicking; Great!

One thing that confused me is why tcp needs to be explicitly enabled; Doesnt sql management studio also use tcp? It was working before I enabled it; Maybe it has some alternative way of connecting?

**Comment by steffengy** [comment]
SQL Server usually uses shared memory (localhost only)/named pipes for connections.
Also something that isn't supported here yet (and only marginally faster).

**Comment by kingcocomango** [comment]
Ah well. Speed isnt an issue, but asking users to fiddle with settings might be.

**Comment by steffengy** [comment]
Yeah but an issue in any other language, Shared memory/Named Pipes are MS-specific while TCP is universally available. Also with good documentation it's in a working state within 5 minutes.
Of course it's an issue if you first have to look through several errors to get it working.

**Comment by kingcocomango** [comment]
I don't disagree. I meant users of what I intend to make using this library, not users of the library :)

**Comment by steffengy** [comment]
Until then it might be implemented already :)
Atleast implementing named-pipes (which bring the most benefit) is quite possible,
just not quite the highest priority currently.

**Comment by kingcocomango** [comment]
I've gone through the docs and I'm having trouble .get ing strings, decimals and datetimes from a row
The naive approach with let foo : String = row.get(x) causes
`
 the trait `tiberius::types::FromColumnData<'_>` is not implemented for `std::string::String`

error[E0277]: the trait bound `std::string::String: tiberius::types::FromColumnData<'_>` is not satisfied
`

**Comment by steffengy** [comment]
For strings use `&str` (which doesn't copy the entire string).
For decimals `f64`. 

For datetimes you currently have to use `NaiveDateTime` of the chrono-crate
(The internal types are not exposed yet, that's also why some documentation for that is not in the documentation)

**Comment by kingcocomango** [comment]
Hmm, that got it to compile but then when Irun it I get 
```
 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Conversion("cannot interpret the given column data as an &\'a strvalue")', src\libcore\result.rs:859
stack backtrace:
```
at the first let foo : &str = row.get(1)
Printing the debug info on the row itself gives this, in case it helps
```
, MetaDataColumn { base: BaseMetaDataColumn { flags: CDF_NULLABLE | CDF_UPDATEABLE, ty: VarLenSized(NVarchar, 200, Some(Collation { info: 13632521, sort_id: 52 })) }, col_name: "foobar" }
```

**Comment by steffengy** [comment]
That is actually more helpful than thought.
In the future I guess I'll change the error message to print the column data to make error finding easier.

The problem is `CDF_NULLABLE` which means that the column is nullable.
So my guess would be that you're actually getting `null` back.
If that's indeed the case you should be using `Option<&str>` instead.

**Comment by kingcocomango** [comment]
I can gurantee that that cell isnt empty in the table, but I will try option and report back

**Comment by steffengy** [comment]
```rust
println!("{:?}", row);
```
should print the entire data of the row, could you try that?
(where row is the same variable you call `.get` on)

**Comment by kingcocomango** [comment]
My gurantee was wrong :D
I accidently reordered the select relative to the table in sql manager, it was indeed null and switching to Option<&str> now correctly pulls all the row data.

That print is how I get the debug info, 

I did not notice the "columns" array that seems to have all the data. Is that publically accessible?

**Comment by steffengy** [comment]
No you can't access that publicly.
It's just that `Debug` is implemented for Row which prints all the underlying data, which
is really useful for debugging.

You can access columns by name or index, so is there anything you can't do
or are you just asking out of curiosity?

**Comment by kingcocomango** [comment]
Just out of curiosity.
I understand that it can be printed but not be accessible to lib users, that's why I asked :)

That solves all the db access issues, next will be writing to it; But I'm not doing that today. Btw, does `row` have an iterator?

**Comment by steffengy** [comment]
No there currently isn't any iterator for `row`.
For my use I wouldn't really have a usecase for an iterator there,
since i mostly just .get() the columns I want by name.

Could you explain your usecase a bit, so I can think about what solution
would be the best fit?

**Comment by kingcocomango** [comment]
Read a table from a db, search through another foreign-keyed table, parse what I find for certain flags, go back and modify the first table based on what I found.

I asked about an iterator because I had to write row.get(X) 30 times just now; maybe a destructuring into a structure or something would be better though I guess that outside the scope of this project and more of an ORM layer.

**Comment by steffengy** [comment]
So if there was a `columns` method that returns the amount of columns,
you'd already be able to use a simple for loop and that problem would already be solved,
right?

**Comment by kingcocomango** [comment]
Yup, a way to query the column count would let me use loops or make my own iterator or etc.
Oh, do you mean there's already a columns method ?

**Comment by steffengy** [comment]
No there strangely isn't (yet), just trying to understand the issue.

Implementing an iterator wouldn't work (except for the edge case that all those columns are the same type, due to generics, since an iterator's items all have the type `T`).

**Comment by steffengy** [comment]
Implemented in the latest master.

If you want to test/use it already I suggest using something like:
```toml
tiberius = { git = 'https://github.com/steffengy/tiberius' }
```
in your `cargo.toml`.

(Since you might or might not have to wait a while for the next release,
not sure when I'll do that)

**Comment by kingcocomango** [comment]
So now im getting to write to the DB and I'm wondering if there is a better way than generating large complex strings and using simplequery?

As I understand and_then is from Tokio , but for_each_row ? 
Also inserts statement.for_each_row does nothing, I assume because it returns an empty table

**Comment by steffengy** [comment]
> generating large complex strings

What exactly do you mean?
For inserting/updating (write-only) use `exec`/`simple_exec` with `single`.
For reading use `query`/`simple_query` with `for_each_row`.

Generally do only use the `simple` variants when not using parameters/user-specified data.

> As I understand and_then is from Tokio , but for_each_row ?

Yes, for_each_row is a part of tiberius.

**Comment by kingcocomango** [comment]
Its not really clear to me *how* to use the non-simple variants, I understand the simple ones take a regular SQL statement as a string, and inserting into the DB for me currently is using an object to form a single large string to pass off to simple_exec

**Comment by steffengy** [comment]
An example for the non-simple ones is in the [docs](https://docs.rs/tiberius).
For the non-simple ones you basically can bypass this string building 
**which for user-specified data is a high security risk, hence the warning in the DOCS.**
and directly use prepared statements/bind parameters.

**Comment by kingcocomango** [comment]
Oh, didn't find the example. Yes I understand and agree re: security risk.

**Comment by steffengy** [comment]
The example is very recent, I added it for the 0.2.1 release, forwhich
I had to improve the documentation a bit.
