### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by davidpodhola** [steffengy/tiberius#24]
I am getting this error at [ParseToken](https://github.com/steffengy/tiberius/blob/master/tiberius/src/tokens.rs#L435); the value is `None`.

It appears [here](https://github.com/hsharpsoftware/rust-realworld-example-app/blob/master/server/src/main.rs#L620) when multiple rows are returned (gets fixed by using `TOP 1`).

**Comment by steffengy** [comment]
I'll try to get this reproduced.
multiple rows alone don't seem to cause this (thats covered by tests)

maybe related to multiple rows & columns and not only small data.

If you have a small query to reproduce (preferably without any tables,
e.g. just a union select, as in all test cases), that'd be helpful.

**Comment by davidpodhola** [comment]
Thanks, will try.

**Comment by davidpodhola** [comment]
I can confirm this is somehow related to the amount of data returned. This happens when the number of rows returned is over some threshold.

**Comment by steffengy** [comment]
@davidpodhola 
Can you test again?

**Comment by davidpodhola** [comment]
Sure, but the tiberius update updated chrono too and now I am getting

the trait `tiberius::types::FromColumnData<'_>` is not implemented for `chrono::NaiveDateTime`

Any advise? Thanks!

**Comment by steffengy** [comment]
You'll have to update chrono in your cargo.toml aswell, did you already try that?

**Comment by davidpodhola** [comment]
Sorry, overlooked one, thanks. And yes, it is fixed, very happy, thank you very much!
