### ISSUE TITLE
Example "create table #temp" doesn't work with exec()

### ISSUE THREAD

**Issue by adlerd** [steffengy/tiberius#30]
The example in the documentation of ```create table #Temp``` command followed by some use of the table like ```insert into #Temp``` doesn't work when simple_exec is replaced with exec (and the necessary changes to make it compile).

Specifically, the below script succeeds when ```--simple``` is passed, but panics otherwise with a message from the server, ```message: "Invalid object name \'#Temp\'."```.
```rust
//! ```cargo
//! [dependencies]
//! clap = "2"
//! futures = "0.1"
//! tiberius = { git = "https://github.com/steffengy/tiberius", rev = "0380636ab0660f7186eead91fd492e4979623cc4" }
//! tokio-core = "0.1"
//! ```

#[macro_use]
extern crate clap;
extern crate futures;
extern crate tokio_core;
extern crate tiberius;

use futures::Future;
use std::borrow::Cow;
use tiberius::{DynamicConnectionTarget, ConnectParams, SqlConnection, EncryptionLevel, AuthMethod};
use tiberius::stmt::ResultStreamExt;
use tokio_core::reactor::Core;

const CT_QUERY: &str = r"
create table #Temp (Name nvarchar(max));
";
const IJ_QUERY: &str = r"
insert into #Temp (Name)
values ( 'foo' )
";

fn prepare_connection(host: Cow<'static, str>) -> (DynamicConnectionTarget, ConnectParams) {
    use std::net::ToSocketAddrs;
    let addrs = (host.as_ref(), 1433u16)
        .to_socket_addrs()
        .unwrap()
        .next()
        .unwrap();
    let mut params = ConnectParams::new();
    params.host = host;
    params.ssl = EncryptionLevel::Required;
    params.auth = AuthMethod::SSPI_SSO;
    params.trust_cert = true;
    params.target_db = None;
    (DynamicConnectionTarget::Tcp(addrs), params)
}

fn main() {
    let matches = clap_app!(@app (app_from_crate!())
            (@arg HOST: --host +takes_value +required "db hostname")
            (@arg SIMPLE: --simple "use simple_exec")
        ).get_matches();

    let mut core = Core::new().unwrap();
    let params = prepare_connection(matches.value_of("HOST").unwrap().to_string().into());

    let conn = SqlConnection::connect(core.handle(), params);
    if matches.is_present("SIMPLE") {
        let f = conn.and_then(|conn| conn.simple_exec(CT_QUERY).single())
            .and_then(|(rows, conn)| {
                println!("CREATED TABLE {}", rows);
                conn.simple_exec(IJ_QUERY).single()
            })
            .map(|(rows, _)| {
                println!("INSERTED {}", rows);
                ()
            });
        core.run(f).unwrap();
    } else {
        let f = conn.and_then(|conn| conn.exec(CT_QUERY, &[]).single())
            .and_then(|(rows, conn)| {
                println!("CREATED TABLE {}", rows);
                conn.exec(IJ_QUERY, &[]).single()
            })
            .map(|(rows, _)| {
                println!("INSERTED {}", rows);
                ()
            });
        core.run(f).unwrap();
    }
}
```

I took a look into the source and I believe the relevant difference between simple_exec and exec is that simple_exec seems to flush a buffer sitting in front of the connection. I didn't fully grok the whole implementation.

**Comment by steffengy** [comment]
This isn't an issue with tiberius but about what prepared statements entail about scopes.

> Prepared statements cannot be used to create temporary objects on SQL Server. Prepared statements cannot reference system stored procedures that create temporary objects, such as temporary tables.[...]

https://technet.microsoft.com/en-us/library/ms175528(v=sql.105).aspx

**Comment by adlerd** [comment]
Yikes. Is it within the scope of tiberius to provide safe argument interpolation without prepared statements?

**Comment by steffengy** [comment]
No it isn't.

Is there a reason you cannot simply use a `simple_exec` to create the temporary table?

I cannot think of any case where you'd need prepared arguments for the creation part.
So doing `simple_exec()` and then `exec()` with parameters seems fine to me,
what isn't covered by that for you?

**Comment by adlerd** [comment]
Ah, you're right; I misread the linked document to say you can't reference temporary objects at all; very different! I guess this would still preclude the "select into" syntax (with parameters) but I think that can be split into create/insert mechanically.

**Comment by steffengy** [comment]
Closing since this is due to MSSQL's design and can't be addressed on a library level.
If you really need something like this you'll need to use global temporary tables (`CREATE TABLE ##t`).
