### ISSUE TITLE
Crash: invalid token received 0x0

### ISSUE THREAD

**Issue by agalakhov** [steffengy/tiberius#33]
Hi,

doing a SELECT query from the view results in a crash in transport.rs, line = 548. The crash seems to be semi-random but reproducible. It is caused by one of two our queries, both are SELECT TOP 1 a, b, c FROM some_view WHERE ... and nothing else.

**Comment by steffengy** [comment]
Is the query executed using `.query()` or `.simple_query()`?
How many rows does the query return?

A trivial `select TOP 1 a, b, c FROM (SELECT 1 as a, 2 as b, 3 as c) a` isn't enough to reproduce.

**Comment by agalakhov** [comment]
The precise query is
"SELECT * FROM [rs_session_reservations] WHERE [uid] = @P1 AND [session] = @P2"
Here, [uid] is bigint and session is varchar. The "*" means multiple fields that are expected to be varchar.

Upd: after changing one of fields from varchar(MAX) to varchar(something else) I now get a hand instead of crash. That is, the future never finishes.

**Comment by agalakhov** [comment]
Important is, it depends somehow on the structure of the database. In a test with a hardcoded table of varchars it does not happen.

A possible cause is the NULL value. It is still not known (we debug this right now), but manually replacing the NULL with something else seems to help. Strange, the test had NULLs as well and it worked.

**Comment by agalakhov** [comment]
More news: it is random.

**Comment by steffengy** [comment]
Can you provide a table schema + the required test data which is required to trigger this bug as SQL script or is it even too random for that?

**Comment by agalakhov** [comment]
Unfortunately it only happens on our semi-production database which contains sensitive data, and it is not triggered without the actual contents.

**Comment by steffengy** [comment]
I think to reproduce the following might be enough:
- column types (a list such as `VARCHAR(MAX), VARCHAR(50), int, ...`)
- A "anonymized" export of rows created by
`SELECT DATALENGTH(col1), DATALENGTH(col2), DATALENGTH(col3), ...`

Is that feasible?

**Comment by steffengy** [comment]
> Is the meaning of 0x00 actually documented?

0x00 usually indicates that too much or not enough is read.
Then it interprets a part of the value or of the next token as token,
which results into an invalid token being read.

I'll still try to reproduce this, but it's a bit like finding a needle in a haystack,
so it might take some time.

**Comment by agalakhov** [comment]
Ok, I got the point. I'll try to find out what's happening. As it is 100% reproducible in our system, I hope I'll get some precise debug logs tomorrow.

**Comment by steffengy** [comment]
Just to be totally sure:
You're using atleast version 0.2.2 (My assumption is master), right?

**Comment by agalakhov** [comment]
Yes, we're using the master branch. Updating to master is the first step to fix mysterious crashes, anyway.

As the first step I'd remove panic! here and replace it with an Err. The server is external to us, and an external message should not crash the program even if it is incorrect from our point of view. I'll do that.

**Comment by steffengy** [comment]
Yeah there're quite a few bad panics, be aware that you cannot reuse/recover the
connection after such an error.

**Comment by agalakhov** [comment]
That is, the function with such an error must consume the connection, while the non-fatal error should return the connection back:
```
enum Error {
    NotSoBad(Connection, ...),
    VeryBad(...),
}
```

**Comment by steffengy** [comment]
Actually it shouldn't even be a problem, since StateStream will not return the connection on an error.
(And non-fatal expected errors are handled internally, so it should already be good)

**Comment by steffengy** [comment]
The distinction between fatal and non-fatal errors is not simple (and often depends on the context).
Currently errors are handled as fatal errors, which should be sufficient.
(The connection won't make any progress, even if polled, which should not happen after an error)

**Comment by agalakhov** [comment]
Ok, I found why the error was hard to reproduce (and the possible cause).

This happens if:
* I have multiple SQL connections (actually 4), and
* two queries are processed in parallel in different Tokio futures.

One of the queries is actually just "SELECT 0", another one is the complex one.

**Comment by steffengy** [comment]
So you're not using 2 nested queries but 2 parallel queries that run on the same thread on different connections? Both should work.

**Comment by agalakhov** [comment]
With just one connection this happens as well. This seems to happen if a query comes immediately after an "SELECT 0".

Anyway, something seems not to be cleaned up completely.

**Comment by agalakhov** [comment]
> So you're not using 2 nested queries
We have two (well, three, the 3rd is "SELECT 0") queries but there are many Tokio jobs that do them in parallel (they handle user logins). The "SELECT 0" is called every few seconds to verify the database is still there.

The error seems to happen if "SELECT 0" somehow clash with another query. Which "can't happen" since the connection is only returned when I'm done with it, but... it happens somehow. Maybe even on the SQL server side.

Right now I'm trying to further reduce the test case.

**Comment by agalakhov** [comment]
The code that actually causes the crash is
```
    let mut lp = Core::new().unwrap();
    let job = SqlConnection::connect(lp.handle(), SQL).and_then(|conn| {
       conn.query("SELECT [uid] FROM [crash] WHERE [uid] = @P1", &[&56])
            .and_then(|rs| rs.collect()).collect()
            .and_then(|(_, conn): (Vec<Vec<QueryRow>>, _)| Ok(conn))
    }).and_then(|conn| {
        conn.query("SELECT 0", &[])
            .and_then(|rs| rs.collect()).collect()
            .and_then(|(_, conn): (Vec<Vec<QueryRow>>, _)| Ok(conn))
    }).and_then(|conn| {
        conn.query("SELECT [uid] FROM [crash] WHERE [uid] = @P1", &[&56])
            .and_then(|rs| rs.collect()).collect()
            .and_then(|(_, conn): (Vec<Vec<QueryRow>>, _)| Ok(conn))
    });
    lp.run(job).unwrap();
```

The contents of the database is
```
CREATE TABLE crash (uid bigint NOT NULL)
INSERT INTO crash (uid) VALUES (56)
```

**Comment by steffengy** [comment]
Reproduced & Reduced:

```rust
 #[test]
    fn test_crash() {
        let mut lp = Core::new().unwrap();
        let conn = new_connection(&mut lp);
        let job = 
            conn.query("SELECT [uid] FROM (select cast(1 as bigint) as uid) b", &[])
                .for_each_row(|_| Ok(()))
                .and_then(|conn| {
                    conn.query("SELECT 0", &[])
                        .for_each_row(|_| Ok(()))
                }).and_then(|conn| {
                    conn.query("SELECT [uid] FROM (select cast(1 as bigint) as uid) b", &[])
                        .for_each_row(|_| Ok(()))
                });
        lp.run(job).unwrap();
    }
```

Now looking into what's going on, it seems possibly related to prepared statements.

**Comment by steffengy** [comment]
@agalakhov 
Should be fixed in the latest master.
Thanks again for tracking this down.

Let me know if there's anything else!

**Comment by agalakhov** [comment]
Thank you, it works for me!
