### ISSUE TITLE
Hiding the documentation for `SqlConnectionNew` makes it difficult to use

### ISSUE THREAD

**Issue by shepmaster** [steffengy/tiberius#35]
```rust
#[doc(hidden)]
pub enum SqlConnectionNew
```

Does it implement `Future`? `Stream`? I have no way of knowing without diving into the source.

**Comment by steffengy** [comment]
@shepmaster 
Yeah that part was really a mess, far better now.

Thanks for reminding me to finally take care of that.

Is this resolved from your perspective now?

**Comment by shepmaster** [comment]
It certainly appears better. You can see the solution I constructed [here](https://stackoverflow.com/q/46344602/155423).
