### ISSUE TITLE
Tiberius goes into an infinite loop on input/output errors

### ISSUE THREAD

**Issue by agalakhov** [steffengy/tiberius#36]
Hi,

I observed an infinite loop with 100% CPU consumption if the SQL server does not work properly.

How to reproduce: try to connect to a server that bans your IP address multiple times (the error must be "Client with IP address 'XXXX' is not allowed to access the server."). After less than 10 attempts there will be an infinite loop.

The stack trace shows that we're in the following loop (file transport.rs):
```
674            while self.missing > 0 {
675                let amount = try_nb!(self.io.read(&mut self.hrd[offset..]));
676                self.missing -= amount;
677                offset += amount;
678            }
```

If the connection is closed by the server, `read()` probably returns `Ok(0)`  as usual. This results in an infinite loop.

The second loop at line 688 may have the same issue. It is possible not to repeat the loop by using the same buffer for the header and the data? Or, better, to use tokio_proto here?

Regards,
Alexey

**Comment by steffengy** [comment]
Not using the same buffer is an optimization, that is intended to allow zero-copy access to medium-sized column data.
A previous version of this library actually used tokio-proto, which was a utterly unfit choice for
this kind of client/server communication and also hard to fit into an API model similar
to the current one. 
It's just too generic to properly expose what we want here, which is why
doing it on a lower-level provides more flexibility here.

I'll look into this soon. How critical is this on your side?

**Comment by agalakhov** [comment]
Not very critical, as it doesn't harm unless there is an SQL connection problem.

The solution is pretty straightforward: check `amount` and return an error if it is 0 (which is the same as "connection reset by peer" in this case).

**Comment by agalakhov** [comment]
P.S. To optimize access, I would copy the header. An extra system call costs more, so it is wise to read as much as possible (more than one packet) in a single `read()` call and then parse.

**Comment by steffengy** [comment]
Well assuming a packet size of 8KB, this would require an additional memcpy of 8kb-8b
(to ensure the tokenstreams contained in contiguous packets is contiguously stored in memory,
and not subdivided by those packet headers, to allow zero-copy access to column data).

That memcpy will be slower than an additional system call
(which is only a copy from network buffers, that's pretty much ensured by using TCP).

Atleast that's the theory, the code could be changed quite easily, but it's definitely
something that should be benchmarked before settling on a solution.

**Comment by steffengy** [comment]
@agalakhov 
Atleast the instant loop should be gone, not sure if it will work gracefully though, let me know!

**Comment by steffengy** [comment]
iovec/readv that mio provides would be better (basically just a maintained version of vecio), but it'ss possible sure.
It's also something I'd want to benchmark though, to ensure it's really faster.

Added to the general TODO list, unfortunately there some more critical points there too.
