### ISSUE TITLE
Doesn't allow for InstanceName in connection string

### ISSUE THREAD

**Issue by icdts** [steffengy/tiberius#37]
https://github.com/steffengy/tiberius/blob/0737ec3b6a1bbc658e6452405d8e038aea611e0c/tiberius/src/lib.rs#L751

From [here:](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.connectionstring(v=vs.110).aspx)
> Data Source must use the TCP format or the Named Pipes format.
> 
> TCP format is as follows:
> - tcp:\<host name>\<instance name>
> - tcp:\<host name>,\<TCP/IP port number>

When you try to execute a valid string like:
> "server=tcp:ServerName\\Instance;Trusted_Connection=Yes;trustServerCertificate=true"

You get the error:
> thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', C:\projects\rust\src\liballoc\vec.rs:1551:10
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

Because parts[1] doesn't exist.

I validated the connection string in powershell:
```
$conn = New-Object System.Data.OleDb.OleDbConnection

$conn.ConnectionString = "Provider=SQLNCLI11;server=tcp:ServerName\Instance;Trusted_Connection=Yes;trustServerCertificate=true"

$conn.Close()

$conn.Open()
```
And it opened a connection fine.  Had to remove the provider for passing into the rust call, not sure if that is normal/okay or not.

**Comment by gugi9000** [comment]
This might be related to #4. Or actually the other way around.

Just making the comment in order to link the issues for future reference :-)

**Comment by icdts** [comment]
@steffengy Just a misunderstanding yes, thanks for fixing

**Comment by steffengy** [comment]
Will be in the 0.3 release, master basically already has a working implementation.
(it doesn't deal with timeouts yet, so not quite polished)
