### ISSUE TITLE
Sending NULL as value in prepared statement

### ISSUE THREAD

**Issue by jonhoo** [steffengy/tiberius#38]
Unless I'm missing something in the set of implementors of [`ToSql`](https://docs.rs/tiberius/0.2.2/tiberius/ty/trait.ToSql.html), there is no way to send a `NULL` as a parameter to a prepared statement. Is this omission intentional? If not, how might one go about sending a `NULL`?

**Comment by steffengy** [comment]
That's right. 
You might be able to trick the SQL Server by using an empty string ("") as a very quick & dirty workaround (which likely will require casting).

That should be quite easy to fix though, I'll look into it.

**Comment by jonhoo** [comment]
Implementing `ToSql` for `Option<T> where T: ToSql` seems like a pretty decent way to go about it, and it's nicely symmetrical with how getting column values handles `NULL`.

**Comment by steffengy** [comment]
That's what I'm looking into right now :)
Should be done in a few minutes.

**Comment by steffengy** [comment]
@jonhoo 
Let me know if the latest master works for you.

**Comment by jonhoo** [comment]
My code at least compiles with `Option`, so that's a step in the right direction! Will take a little time before I get to try to run it, but I'll report back when I do. Thanks for the quick turnaround!

**Comment by jonhoo** [comment]
Yup, seems to work correctly! :)
