### ISSUE TITLE
Build error on nightly

### ISSUE THREAD

**Issue by madmaxio** [steffengy/tiberius#44]
channel bindings method not found in the current scope for type "I"

Am I doind something wrong perhaps?

**Comment by madmaxio** [comment]
With this exactly:

tiberius = { path = "https://github.com/steffengy/tiberius", default-features=false, features=["chrono"] }

Will check what's going on here.

**Comment by steffengy** [comment]
Can't reproduce.
Can you provide more input:
-  an exact error message (that the compiler gives you, including the information WHERE that error occurs)
- the exact nightly version
- the OS/platform you're building for
- sample project, possible a reduced test case, to reproduce

**Comment by madmaxio** [comment]
Compiling tiberius v0.2.3
error[E0599]: no method named `channel_bindings` found for type `I` in the current scope
   --> /home/maxim/.cargo/registry/src/github.com-1ecc6299db9ec823/tiberius-0.2.3/src/lib.rs:261:33
    |
261 |         self.transport.inner.io.channel_bindings()
    |                                 ^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `tiberius`.

To learn more, run the command again with --verbose.

rustc 1.25.0-nightly (8ccab7eed 2018-01-31)

ubuntu server 17.10

It's just an empty project with one dependency line

tiberius = { version = "*", default-features = false, features=["chrono"] }
