### ISSUE TITLE
How to get a collection of values from for_each_row?

### ISSUE THREAD

**Issue by madmaxio** [steffengy/tiberius#45]
Is there a way to collect a vec and get it outside of the future?

**Comment by steffengy** [comment]
currently `.single().collect()` should work

**Comment by steffengy** [comment]
Actually that doesn't work at the moment, you'll have to collect the rows manually.

**Comment by steffengy** [comment]
In the latest master and the usability improvements coming with 0.3 it works using just `.collect()`.

**Comment by madmaxio** [comment]
Can you provide an example please of what works with the master now?

**Comment by steffengy** [comment]
@madmaxio 
```rust
extern crate futures;
extern crate futures_state_stream;
extern crate tokio_core;
extern crate tiberius;
use futures::Future;
use futures_state_stream::StateStream;
use tokio_core::reactor::Core;
use tiberius::SqlConnection;
use tiberius::query::QueryRow;

fn main() {
   let mut lp = Core::new().unwrap();

   let conn_str = "server=tcp:localhost,1433;integratedSecurity=true;".to_owned();

   let future = SqlConnection::connect(lp.handle(), conn_str.as_str())
       .and_then(|conn| {
           conn.simple_query("SELECT 1+2").collect().and_then(|(rows, conn)| {
                println!("{:?}", rows.len());
                Ok(())
           })
       });
   lp.run(future).unwrap();
}
```

rows is a `Vec<QueryRow>` so you can get whatever columns you want for each row.

**Comment by madmaxio** [comment]
extern crate futures;
extern crate futures_state_stream;
extern crate tokio_core;
extern crate tiberius;

use futures::Future;
use futures_state_stream::StateStream;
use tokio_core::reactor::Core;
use tiberius::SqlConnection;
use tiberius::query::QueryRow;
use futures_state_stream::StateStream;

fn main() {
    let mut lp = Core::new().unwrap();

    let conn_str = "server=tcp:localhost,1433;integratedSecurity=true;".to_owned();

    let future = SqlConnection::connect(lp.handle(), conn_str.as_str())
        .and_then(|conn| {
            conn.simple_query("SELECT 1+2").collect().and_then(|(rows, conn)| {
                println!("{:?}", rows.len());
                Ok(())
            })
        });
    lp.run(future).unwrap();
}

![default](https://user-images.githubusercontent.com/8720539/36354469-0f8afe64-14e6-11e8-9179-cf76a87dc5c3.png)

**Comment by steffengy** [comment]
As mentioned by the error, you're missing the
```
use futures_state_stream::StateStream;
```
(potentially due to using future_state_stream 0.2 instadof 0.1?)

**Comment by madmaxio** [comment]
Ah, fixed the version, true. I can even return the rows now from the future, that's pretty cool.

**Comment by steffengy** [comment]
Yeah 0.3 is much better in terms of ergonomics, the chance to fix some previous design decisions :)

**Comment by madmaxio** [comment]
Closing, thx a lot.

**Comment by madmaxio** [comment]
By they way, at the moment rows is a Vec<QueryStream<std::boxed etc, not a of Vec<QueryRow>. How to convert it to Vec<QueryRow> ?

**Comment by steffengy** [comment]
For me that sounds like youre not using the latest master, try running cargo update.

**Comment by madmaxio** [comment]
Oh my god, worked! Thx again.
