### ISSUE TITLE
can't figure out how to use a connection in a loop

### ISSUE THREAD

**Issue by bbigras** [steffengy/tiberius#49]
It seems that when I do a query the connection object is consumed and I need to wait with then() or something similar to get the connection back. I can't figure out how to do that in a loop (like a stream.for_each which use the connection for each item).

Is there any connection pooling? if so I might just use a new connection object every time.

**Comment by steffengy** [comment]
What do you want to do?

A connection can only execute one query at the time, so if you indeed want to execute multiple queries concurrently, yes you'll need multiple connections.

If you just want to execute queries consecutively you'll have to take the connection back.
With a prepared statement this would look like:
https://github.com/steffengy/tiberius/blob/a6e3347e7fcd198bf46955853239aad5a79f726d/tiberius/src/lib.rs#L1218-L1227

**Comment by bbigras** [comment]
Sorry for the late reply.

Your sample code worked great for what I was trying to do when I opened this issue. But I have another case today.

I would like to do something like the following code. I think it would be better than using `lp.run(future).unwrap()` since it wouldn't block. I know I could use spawn() with channels but I would prefer a simpler way if possible. Maybe with an `Rc<RefCell<Transaction>>` or something.

```rust

fn something(
    t: tiberius::Transaction<std::boxed::Box<tiberius::BoxableIo>>,
) -> impl Future<Item = (), Error = Error> {
    let mut stream = stream::iter_ok::<_, ()>(vec![1, 2, 3]);

    let f = stream.for_each(|v| t.exec("SQL query", &[&v]));

    return f;
}
```

**Comment by steffengy** [comment]
You should be able to do something like 
```rust
stream.fold(t, |(tx, v)| tx.exec("SQL query"), &[&v]).and_then(|(result, tx)| {
   ... handle result ...;
   tx
}))
```

**Comment by bbigras** [comment]
It works. Thank you very much. For the crate too. I was able to use Rust for this project thanks to this crate.

**Comment by brokenthorn** [comment]
I have a similar problem. I'm implementing `r2d2::ManageConnection`. One of its fn's, [`is_valid`](https://docs.rs/r2d2/0.8.2/r2d2/trait.ManageConnection.html), borrows the connection, mutably. The purpose of the function is to check if the connection is still... valid. The way I want to do this is to query the SQL Server for the result of "SELECT 1" like it is suggested to do. The problem is that tiberius' `SqlConnection` consumes self when calling `query`, which inside `is_valid` can't happen, because it's already borrowed in this context. Any suggestions?
```
fn is_valid(&self, conn: &mut Self::Connection) -> Result<(), Self::Error> {
    let sql_str = "SELECT 1";
    let stmt = conn.prepare(sql_str);
    let future = conn
        .query(stmt, &[])
        .for_each(move |x| {
            let result: i32 = x.get(0);
            // ...
            Ok(())
        });
    // now run the future and unwrap it
    match future.wait() {
        Ok(_) => { Ok(()) }
        Err(tiberius_error) => Err(
            MSSQLConnectionManagerError(Errors::WrappedTiberiusError(tiberius_error))
        ),
    }
}
```

```
error[E0507]: cannot move out of borrowed content
   --> src/persistence/mssql.rs:112:22
    |
112 |         let future = conn
    |                      ^^^^ cannot move out of borrowed content

error: aborting due to previous error

For more information about this error, try `rustc --explain E0507`.
```
