### ISSUE TITLE
Can't pass string as parameter to query

### ISSUE THREAD

**Issue by madmaxio** [steffengy/tiberius#50]
When using query function and passing &[&my_string] as params, I get compile error:

```
&[&prm]
  ^^^^ the trait `tiberius::prelude::ToSql` is not implemented for `std::string::String
```

**Comment by steffengy** [comment]
Well it expects `&ToSql` which is only implemented by `&str`.
So something like `&prm.as_str()` should work (maybe even without the `&`).

**Comment by madmaxio** [comment]
Worked with & as_str(), thx.
