### ISSUE TITLE
Error when passing String param

### ISSUE THREAD

**Issue by madmaxio** [steffengy/tiberius#52]
Getting weird error when passing utf8  non english character string param:

```
thread 'test_main' panicked at 'called `Result::unwrap()` on an `Err` value: Server(TokenError { code: 4002, state: 2, class: 16, message: "The incoming tabular data stream (TDS) protocol stream is incorrect. The stream ended unexpectedly.", server: "SRV-DB-08\\SQL01", procedure: "", line: 1 })', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
test test_main ... FAILED
```

Same behaviour is described here: https://stackoverflow.com/questions/9082605/django-freetds-pyodbc-error-at-inserting-russian-letters?rq=1

**Comment by steffengy** [comment]
Could you provide some small testcase/query that reproduces that behavior so I can investigate?

**Comment by madmaxio** [comment]
`exec("insert into users (name) values (@P1)", &[&"Ааабб"]);`

P1 is in russian

**Comment by steffengy** [comment]
@madmaxio should be fixed in master, though I doubt this is the last one of those issues.

**Comment by madmaxio** [comment]
Works after latest comment, closing.
