### ISSUE TITLE
What is the simplest way to only retrieve one row?

### ISSUE THREAD

**Issue by bbigras** [steffengy/tiberius#58]
For the queries when we only expect 1 row.

I don't think I can use for_each() since it returns (). I would like the future to return the value. Right now I'm doing `collect().and_then()` and only using the first item of the vector.

**Comment by steffengy** [comment]
I don't think there's a better way than `collect()` and using one row.
Using `collect` you can ensure that actually your query only returns one row.

I'd use something like:
```rust
result.and_then(|(rows, conn)| {
      assert_eq!(rows.len(), 1); // TODO: propagate errors if you expect them regularily
      let row = &rows[0];
      
      // or if you need mutable access (do not forget to use mut rows in and_then)
      // let row = rows.remove(0);
})
```

Anything else you would expect/wish you could do?

**Comment by bbigras** [comment]
> Anything else you would expect/wish you could do?

No. I think I'm good for now. Thanks!
