### ISSUE TITLE
NUMERIC(12) doest not work

### ISSUE THREAD

**Issue by schleumer** [steffengy/tiberius#6]
When there's a `NUMERIC(12)` column i got a system panic.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ProtocolError(InvalidLength("decimal: length of 12 is unsupported"))', ../src/libcore\result.rs:799
```

**Comment by schleumer** [comment]
If you guide me i can do this by myself and send a pull request.

**Comment by steffengy** [comment]
currently working on an (async) rewrite since this has some serious design flaws.

if you still want to play around with it:
https://github.com/steffengy/tiberius/blob/34eb05952d152183407379a55f8d8a822e6fabc1/src/protocol/types.rs#L513
