### ISSUE TITLE
problem with [varchar](max) fields: thread 'main' panicked at 'assertion failed: *len != 65535'

### ISSUE THREAD

**Issue by bbigras** [steffengy/tiberius#60]
I have a column with a lot of characters (up to 925835 at this time). It's an XML in a varchar(max) field.

```
thread 'main' panicked at 'assertion failed: *len != 65535', /home/bbigras/.cargo/git/checkouts/tiberius-efcdb30e5dbea5fc/c2631ac/tiberius/src/types/mod.rs:453:25
```

the right line is:
https://github.com/steffengy/tiberius/blob/d7b1768674daccf84775cd74fa97b93b254a569c/tiberius/src/types/mod.rs#L456

I'm using c2631ac2dfac3998e98432cd9371c7c31b9fa0e9 right now but I'll update to master.

**Comment by steffengy** [comment]
As a workaround you should be able to cast to nvarchar(max) for now.

**Comment by bbigras-** [comment]
It seems to work. Thank you very much. :+1:

**Comment by bbigras** [comment]
It seems to work. Thank you very much. :+1:

**Comment by steffengy** [comment]
Thish should be fixed in the latest master.

**Comment by bbigras** [comment]
Yes it works. Thanks!!
