### ISSUE TITLE
Multiple issues with example

### ISSUE THREAD

**Issue by toyg** [steffengy/tiberius#63]
The current example at https://docs.rs/tiberius/0.2.3/tiberius/ does not match the `master` branch. Because of #56, working on Mac I'm forced on master. I recovered a working example from tests in source but it has been a bit of a wild ride.

I think it would be useful to have documentation in the repository that tries to match the current status of the branch, at least for master. I'm a real newb with Rust, but if you have any pointer on how this could be achieved, I'd be happy to look into producing a PR of sort.

**Comment by steffengy** [comment]
Yeah you're right, 0.3 is delayed for far too long, I released a 0.3 and adjusted some planning.
Generally you can use `cargo doc` to generate matching documentation locally.

**Comment by toyg** [comment]
That's a great tip, thanks!
