### ISSUE TITLE
Is it possible to get the connection back after an .into_stream()

### ISSUE THREAD

**Issue by bbigras** [steffengy/tiberius#64]
I like to use streams with [forward()](https://docs.rs/futures/0.1/futures/stream/trait.Stream.html#method.forward) and I would like to run a second query after the first one, something like:

```rust
SqlConnection::connect(conn_str.as_str())
        .map_err(sql_err)
        .and_then(|conn| {
            conn.query(include_str!("query.sql"), &[])
                .map_err(sql_err)
                .into_stream()
                .map(|row| {
                    let code: &str = row.get(0);
                    code.to_string()
                })
                .forward(tx)
                .and_then(|r| {
                    // I don't seem able to get the connection from 'r'
                    conn.simple_exec("create table #Temp(gg int);");

                    Ok(())
                })
        })
```

**Comment by steffengy** [comment]
That example shouldn't work since `StateStream` doesn't have a `forward` method at all.

**Comment by bbigras** [comment]
My example does compile. I think it's because QueryResult implements StateStream and that futures_state_stream::IntoStream implements Stream.

**Comment by steffengy** [comment]
Oh right, I thought this was using https://docs.rs/tiberius/0.3.0/tiberius/stmt/struct.QueryResult.html#method.into_stream (which would make sense if you're executing multiple queries).

But I think that answers your question:

> A Stream yielding the elements of a StateStream and ***discarding its state.***

https://docs.rs/futures-state-stream/0.1.0/futures_state_stream/struct.IntoStream.html

So no it's not possible this way.
