### ISSUE TITLE
milliseconds are lost when using chrono::NaiveDateTime

### ISSUE THREAD

**Issue by bbigras** [steffengy/tiberius#66]
I use a NaiveDateTime to fetch a DATETIME2(7) and insert it back into a DATETIME2(7) in another table but I lose the nanoseconds.

2018-06-22 15:06:36.5930000 becomes
2018-06-22 15:06:36.0000000

I didn't try tiberius::ty::DateTime2.

**Comment by steffengy** [comment]
Let me know, if this doesn't fix most of it.

**Comment by bbigras** [comment]
I got more precision now but it seems
2018-05-15 10:46:11.3230000 becomes
2018-05-15 10:46:11.3200000

**Comment by bbigras** [comment]
Can we re-open this issue?

**Comment by steffengy** [comment]
It's a different issue, but sure (datetime2 being sent as datetime)

**Comment by steffengy** [comment]
@bbigras should be fixed in 1d4c021715d741fc9c60eb737f03f66963f2e1fb

**Comment by bbigras** [comment]
It seems to work. Thanks!
