### ISSUE TITLE
Pick a LICENSE if this is open-source

### ISSUE THREAD

**Issue by Phrohdoh** [steffengy/tiberius#7]
MIT and/or Apache 2 would mesh best with the rest of the ecosystem.

**Comment by steffengy** [comment]
technically it's MIT currently:
https://github.com/steffengy/tiberius/blob/master/Cargo.toml#L9

I'll license the async-rewrite as MIT/Apache2, which hopefully in comparison
to the current master state, won't have many design limitations.

**Comment by steffengy** [comment]
done.

**Comment by Phrohdoh** [comment]
Awesome!
