### ISSUE TITLE
update the futures-state-stream dependency

### ISSUE THREAD

**Issue by bbigras** [steffengy/tiberius#75]
Just to make `cargo outdated` stop complaining. :)

**Comment by steffengy** [comment]
usage-wise it might also be better to switch away from it entirely. (as happening with tokio-postgres)

**Comment by jonhoo** [comment]
Another advantage to bumping the dependency is that we'll get https://github.com/sfackler/futures-state-stream/pull/3, which allows you to get back the `SqlConnection` on error. As observed in #94, there aren't _that_ many cases where you'd be able to keep using the same `SqlConnection` after an error, but having the option would be nice.

**Comment by allquixotic** [comment]
Oof, I spent an hour or two flailing on this until I saw https://github.com/steffengy/tiberius/issues/72 -- sneaky! :( Looking forward to a fix here (or updated example that works with latest version of dependencies).

**Comment by jonhoo** [comment]
@steffengy any updates on this?

**Comment by steffengy** [comment]
@jonhoo 
No, I'm not planning to do this, since there are not really any worth upsides to it.
The eventual restructuring when async/await is around will get rid of the futures-state-stream dependency entirely anyways.
So no immediate plans in that area, I wouldn't expect it before 2020.

**Comment by brokenthorn** [comment]
Steffen, will async/await permit using the connection directly within a
generic connection pool? (Can you move the connection?)

I think last time I tried, it was impossible with something like r2d2.

mar., 18 iun. 2019, 18:51 Steffen Butzer <notifications@github.com> a scris:

**Comment by steffengy** [comment]
Shouldn't make any difference for connection pooling, I think you'll always need 
a pool that supports async, like https://github.com/onesignal/l3-37

**Comment by steffengy** [comment]
Closing this, as futures-state-stream won't be used by the async-implementation in 0.4 anymore.
