### ISSUE TITLE
Is it possible to get the transaction back when there's an error?

### ISSUE THREAD

**Issue by bbigras** [steffengy/tiberius#94]
If I run `tx.exec()` and I get an error, can I get `tx` back? I don't know if an SQL transaction is still usable after a failed query.

**Comment by steffengy** [comment]
It is not, might be related to #75.
For most kinds of errors, the connection is "broken" - so really hard to distinguish, even if we could return it.

**Comment by young-altair** [comment]
Sory to comment here. Just wanna help.
Maybe you can use the approach from within SQL Server itself, inside your Stored Procedure.
```
ALTER PROCEDURE NAME_OF_PROCEDURE
   @params1 int, 
   @params2 int
AS 
BEGIN
BEGIN TRY
	BEGIN TRANSACTION NAMEOFTRANSACTION

--TRANSACTION CODE
--INSERT, UPDATE, DELETE Blablabla

	COMMIT TRANSACTION NAMEOFTRANSACTION
END TRY
BEGIN CATCH 
	IF (@@TRANCOUNT > 0)
  		BEGIN
		    ROLLBACK TRANSACTION NAMEOFTRANSACTION
		    PRINT 'Error detected, all changes reversed'
		END     
END CATCH
END
```
