### ISSUE TITLE
Erro when select a column with float with size 8

### ISSUE THREAD

**Issue by cmbergamo** [steffengy/tiberius#97]
Where I ran the following sql, retun "thread 'main' panicked at 'unsupported fixed type decoding: Float8'"

SELECT c5_num, RTRIM(a1_nome), c5_emissao, (c5_valmerc - c5_valdesc) FROM sc5

The c5_valmerc and the c5_valdesc are float with length 8
![float_error](https://user-images.githubusercontent.com/10077040/55031548-95c3ee80-4fed-11e9-93ca-54385f0bb225.png)

**Comment by steffengy** [comment]
What MSSQL version are you using?

**Comment by cmbergamo** [comment]
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor) 

By the way, thx for sharing your knowledge.

**Comment by steffengy** [comment]
Thanks, fixed.

**Comment by cmbergamo** [comment]
The version 0.3.2 already has the correction for this problem???

**Comment by steffengy** [comment]
0.3.2 is 10 days old, so no, 0.3.3 will have it

**Comment by cmbergamo** [comment]
Ok. Thank you again. Nice work!
